version: "3.7"
services:
  kafka:
    image: bitnami/kafka:3.5
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    volumes:
      - .- /var/lib/kafka:/bitnami
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT1://127.0.0.1:9092,PLAINTEXT2://127.0.0.1:9094
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT1://:9092,PLAINTEXT2://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT1:PLAINTEXT,PLAINTEXT2:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
